In [ ]:
import os
print(os.getcwd())

C:\Users\91880\Car_bhumika.ipynb

In [ ]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\91880\Car_bhumika.ipynb\laptop_price.xls",
    encoding='latin1'
)

df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [ ]:
df.tail()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,IPS Panel Full HD / Touchscreen 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,128GB SSD,Intel HD Graphics 520,Windows 10,1.8kg,638.0
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,IPS Panel Quad HD+ / Touchscreen 3200x1800,Intel Core i7 6500U 2.5GHz,16GB,512GB SSD,Intel HD Graphics 520,Windows 10,1.3kg,1499.0
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,1366x768,Intel Celeron Dual Core N3050 1.6GHz,2GB,64GB Flash Storage,Intel HD Graphics,Windows 10,1.5kg,229.0
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,1366x768,Intel Core i7 6500U 2.5GHz,6GB,1TB HDD,AMD Radeon R5 M330,Windows 10,2.19kg,764.0
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,1366x768,Intel Celeron Dual Core N3050 1.6GHz,4GB,500GB HDD,Intel HD Graphics,Windows 10,2.2kg,369.0

In [ ]:
df.info

<bound method DataFrame.info of       laptop_ID Company                              Product  \
0             1   Apple                          MacBook Pro
1             2   Apple                          Macbook Air
2             3      HP                               250 G6
3             4   Apple                          MacBook Pro
4             5   Apple                          MacBook Pro
...         ...     ...                                  ...
1298       1316  Lenovo                       Yoga 500-14ISK
1299       1317  Lenovo                       Yoga 900-13ISK
1300       1318  Lenovo                   IdeaPad 100S-14IBR
1301       1319      HP  15-AC110nv (i7-6500U/6GB/1TB/Radeon
1302       1320    Asus  X553SA-XX031T (N3050/4GB/500GB/W10)

                TypeName  Inches                            ScreenResolution  \
0              Ultrabook    13.3          IPS Panel Retina Display 2560x1600
1              Ultrabook    13.3                                    1440x900
2               Notebook    15.6                           Full HD 1920x1080
3              Ultrabook    15.4          IPS Panel Retina Display 2880x1800
4              Ultrabook    13.3          IPS Panel Retina Display 2560x1600
...                  ...     ...                                         ...
1298  2 in 1 Convertible    14.0   IPS Panel Full HD / Touchscreen 1920x1080
1299  2 in 1 Convertible    13.3  IPS Panel Quad HD+ / Touchscreen 3200x1800
1300            Notebook    14.0                                    1366x768
1301            Notebook    15.6                                    1366x768
1302            Notebook    15.6                                    1366x768

                                       Cpu   Ram               Memory  \
0                     Intel Core i5 2.3GHz   8GB            128GB SSD
1                     Intel Core i5 1.8GHz   8GB  128GB Flash Storage
2               Intel Core i5 7200U 2.5GHz   8GB            256GB SSD
3                     Intel Core i7 2.7GHz  16GB            512GB SSD
4                     Intel Core i5 3.1GHz   8GB            256GB SSD
...                                    ...   ...                  ...
1298            Intel Core i7 6500U 2.5GHz   4GB            128GB SSD
1299            Intel Core i7 6500U 2.5GHz  16GB            512GB SSD
1300  Intel Celeron Dual Core N3050 1.6GHz   2GB   64GB Flash Storage
1301            Intel Core i7 6500U 2.5GHz   6GB              1TB HDD
1302  Intel Celeron Dual Core N3050 1.6GHz   4GB            500GB HDD

                               Gpu       OpSys  Weight  Price_euros
0     Intel Iris Plus Graphics 640       macOS  1.37kg      1339.69
1           Intel HD Graphics 6000       macOS  1.34kg       898.94
2            Intel HD Graphics 620       No OS  1.86kg       575.00
3               AMD Radeon Pro 455       macOS  1.83kg      2537.45
4     Intel Iris Plus Graphics 650       macOS  1.37kg      1803.60
...                            ...         ...     ...          ...
1298         Intel HD Graphics 520  Windows 10   1.8kg       638.00
1299         Intel HD Graphics 520  Windows 10   1.3kg      1499.00
1300             Intel HD Graphics  Windows 10   1.5kg       229.00
1301            AMD Radeon R5 M330  Windows 10  2.19kg       764.00
1302             Intel HD Graphics  Windows 10   2.2kg       369.00

[1303 rows x 13 columns]>

In [ ]:
df.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [ ]:
df['Cpu Brand'] = df['Cpu'].apply(lambda x: x.split()[0])

df['Cpu Type'] = df['Cpu'].apply(lambda x: " ".join(x.split()[0:3]))

In [ ]:
df['Memory'] = df['Memory'].astype(str)

df['SSD'] = df['Memory'].apply(lambda x: 1 if 'SSD' in x else 0)
df['HDD'] = df['Memory'].apply(lambda x: 1 if 'HDD' in x else 0)

In [ ]:
df['Gpu Brand'] = df['Gpu'].apply(lambda x: x.split()[0])

In [ ]:
df['X_res'] = df['ScreenResolution'].apply(lambda x: x.split()[-1].split('x')[0])
df['Y_res'] = df['ScreenResolution'].apply(lambda x: x.split()[-1].split('x')[1])

df['X_res'] = df['X_res'].astype(int)
df['Y_res'] = df['Y_res'].astype(int)

In [ ]:
df.drop(['Cpu', 'Memory', 'Gpu', 'ScreenResolution'], axis=1, inplace=True)

In [ ]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Ram,OpSys,Weight,Price_euros,Cpu Brand,Cpu Type,SSD,HDD,Gpu Brand,X_res,Y_res
0,1,Apple,MacBook Pro,Ultrabook,13.3,8GB,macOS,1.37kg,1339.69,Intel,Intel Core i5,1,0,Intel,2560,1600
1,2,Apple,Macbook Air,Ultrabook,13.3,8GB,macOS,1.34kg,898.94,Intel,Intel Core i5,0,0,Intel,1440,900
2,3,HP,250 G6,Notebook,15.6,8GB,No OS,1.86kg,575.00,Intel,Intel Core i5,1,0,Intel,1920,1080
3,4,Apple,MacBook Pro,Ultrabook,15.4,16GB,macOS,1.83kg,2537.45,Intel,Intel Core i7,1,0,AMD,2880,1800
4,5,Apple,MacBook Pro,Ultrabook,13.3,8GB,macOS,1.37kg,1803.60,Intel,Intel Core i5,1,0,Intel,2560,1600

In [ ]:
df.count()

laptop_ID      1303
Company        1303
Product        1303
TypeName       1303
Inches         1303
Ram            1303
OpSys          1303
Weight         1303
Price_euros    1303
Cpu Brand      1303
Cpu Type       1303
SSD            1303
HDD            1303
Gpu Brand      1303
X_res          1303
Y_res          1303
dtype: int64

In [ ]:
df.isnull().sum()

laptop_ID      0
Company        0
Product        0
TypeName       0
Inches         0
Ram            0
OpSys          0
Weight         0
Price_euros    0
Cpu Brand      0
Cpu Type       0
SSD            0
HDD            0
Gpu Brand      0
X_res          0
Y_res          0
dtype: int64

In [ ]:
df_encoded = pd.get_dummies(df, drop_first=True)

In [ ]:
df_encoded.head()

,laptop_ID,Inches,Price_euros,SSD,HDD,X_res,Y_res,Company_Apple,Company_Asus,Company_Chuwi,...,Cpu Type_Intel Core i5,Cpu Type_Intel Core i7,Cpu Type_Intel Pentium Dual,Cpu Type_Intel Pentium Quad,Cpu Type_Intel Xeon E3-1505M,Cpu Type_Intel Xeon E3-1535M,Cpu Type_Samsung Cortex A72&A53,Gpu Brand_ARM,Gpu Brand_Intel,Gpu Brand_Nvidia
0,1,13.3,1339.69,1,0,2560,1600,True,False,False,...,True,False,False,False,False,False,False,False,True,False
1,2,13.3,898.94,0,0,1440,900,True,False,False,...,True,False,False,False,False,False,False,False,True,False
2,3,15.6,575.00,1,0,1920,1080,False,False,False,...,True,False,False,False,False,False,False,False,True,False
3,4,15.4,2537.45,1,0,2880,1800,True,False,False,...,False,True,False,False,False,False,False,False,False,False
4,5,13.3,1803.60,1,0,2560,1600,True,False,False,...,True,False,False,False,False,False,False,False,True,False

In [ ]:
df_encoded.columns

Index(['laptop_ID', 'Inches', 'Price_euros', 'SSD', 'HDD', 'X_res', 'Y_res',
       'Company_Apple', 'Company_Asus', 'Company_Chuwi',
       ...
       'Cpu Type_Intel Core i5', 'Cpu Type_Intel Core i7',
       'Cpu Type_Intel Pentium Dual', 'Cpu Type_Intel Pentium Quad',
       'Cpu Type_Intel Xeon E3-1505M', 'Cpu Type_Intel Xeon E3-1535M',
       'Cpu Type_Samsung Cortex A72&A53', 'Gpu Brand_ARM', 'Gpu Brand_Intel',
       'Gpu Brand_Nvidia'],
      dtype='object', length=885)

In [ ]:
df_encoded.drop("laptop_ID", axis=1, inplace=True)

In [ ]:
df_encoded.columns

Index(['Inches', 'Price_euros', 'SSD', 'HDD', 'X_res', 'Y_res',
       'Company_Apple', 'Company_Asus', 'Company_Chuwi', 'Company_Dell',
       ...
       'Cpu Type_Intel Core i5', 'Cpu Type_Intel Core i7',
       'Cpu Type_Intel Pentium Dual', 'Cpu Type_Intel Pentium Quad',
       'Cpu Type_Intel Xeon E3-1505M', 'Cpu Type_Intel Xeon E3-1535M',
       'Cpu Type_Samsung Cortex A72&A53', 'Gpu Brand_ARM', 'Gpu Brand_Intel',
       'Gpu Brand_Nvidia'],
      dtype='object', length=884)

In [ ]:
X = df_encoded.drop("Price_euros", axis=1)
y = df_encoded["Price_euros"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(max_depth=10)
model.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=10)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

print("Accuracy:", r2_score(y_test, y_pred))

Accuracy: 0.6314638391000454

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=100,
    max_depth=15,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

print("Random Forest Accuracy:", r2_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.7423282364893536

In [ ]:
df = pd.read_csv(
    r"C:\Users\91880\laptop.ipynb\laptop_price.xls",
    encoding='latin1'
)

df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [ ]:
import re

def extract_memory(text):
    ssd = 0
    hdd = 0

    if "SSD" in text:
        match = re.search(r'(\d+)GB SSD', text)
        if match:
            ssd = int(match.group(1))

    if "HDD" in text:
        match = re.search(r'(\d+)TB HDD', text)
        if match:
            hdd = int(match.group(1)) * 1024

    return pd.Series([ssd, hdd])

df[['SSD_size', 'HDD_size']] = df['Memory'].apply(extract_memory)

In [ ]:
from sklearn.metrics import r2_score

print("Random Forest Accuracy:", r2_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.7423282364893536

In [ ]:
df.drop("Memory", axis=1, inplace=True)

In [ ]:
df['Ram'] = df['Ram'].str.replace('GB', '').astype(int)
df['Weight'] = df['Weight'].str.replace('kg', '').astype(float)

In [ ]:
df['Cpu Brand'] = df['Cpu'].apply(lambda x: x.split()[0])
df['Cpu Type'] = df['Cpu'].apply(lambda x: " ".join(x.split()[0:3]))
df['Gpu Brand'] = df['Gpu'].apply(lambda x: x.split()[0])

In [ ]:
df['X_res'] = df['ScreenResolution'].apply(lambda x: x.split()[-1].split('x')[0]).astype(int)
df['Y_res'] = df['ScreenResolution'].apply(lambda x: x.split()[-1].split('x')[1]).astype(int)

In [ ]:
df.drop(['laptop_ID', 'Product', 'Cpu', 'Gpu', 'ScreenResolution'], axis=1, inplace=True)

In [ ]:
df = pd.get_dummies(df, drop_first=True)

In [ ]:
X = df.drop("Price_euros", axis=1)
y = df["Price_euros"]

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

rf = RandomForestRegressor(n_estimators=100, max_depth=15)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

In [ ]:
from sklearn.metrics import r2_score

print("New Accuracy:", r2_score(y_test, y_pred_rf))

New Accuracy: 0.773555868196067

In [ ]:
import numpy as np

df['PPI'] = ((df['X_res']**2 + df['Y_res']**2)**0.5) / df['Inches']

In [ ]:
df.drop(['X_res', 'Y_res', 'Inches'], axis=1, inplace=True)

In [ ]:
df = pd.get_dummies(df, drop_first=True)

X = df.drop("Price_euros", axis=1)
y = df["Price_euros"]

In [ ]:
# Step 3: Train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 4: Train Random Forest
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=200,     # more trees = better performance
    max_depth=20,         # deeper trees = better learning
    random_state=42
)

rf.fit(X_train, y_train)

# Step 5: Prediction
y_pred_rf = rf.predict(X_test)

# Step 6: Accuracy
from sklearn.metrics import r2_score

print("Final Accuracy:", r2_score(y_test, y_pred_rf))

Final Accuracy: 0.8151440088787962

In [ ]:
import pickle

pickle.dump(rf, open("laptop_price_model.pkl", "wb"))

In [ ]:
pickle.dump(X.columns, open("columns.pkl", "wb"))

In [ ]:
df.head()

,Ram,Weight,Price_euros,SSD_size,HDD_size,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,...,Cpu Type_Intel Core i7,Cpu Type_Intel Pentium Dual,Cpu Type_Intel Pentium Quad,Cpu Type_Intel Xeon E3-1505M,Cpu Type_Intel Xeon E3-1535M,Cpu Type_Samsung Cortex A72&A53,Gpu Brand_ARM,Gpu Brand_Intel,Gpu Brand_Nvidia,PPI
0,8,1.37,1339.69,128,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,226.983005
1,8,1.34,898.94,0,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,127.677940
2,8,1.86,575.00,256,0,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,141.211998
3,16,1.83,2537.45,512,0,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,220.534624
4,8,1.37,1803.60,256,0,True,False,False,False,False,...,False,False,False,False,False,False,False,True,False,226.983005